### ISSUE TITLE
Problem when opening with --remote-silent

### ISSUE THREAD

**Issue by AgentCosmic** [fholgado/minibufexpl.vim#90]
When I open a file with --remote-silent I will have an empty buffer [1].
After open some other files and I attempt to close one buffer with :bd, vim quits.

This is message comes up for the first file:
![image](https://f.cloud.github.com/assets/1035714/667998/433e07da-d803-11e2-86ef-f070ed822106.png)

This comes up for the second file:
![image](https://f.cloud.github.com/assets/1035714/668004/60d77fd8-d803-11e2-87e0-923e5fa52912.png)

**Comment by weynhamz** [comment]
Can you provide a more detailed procedure to reproduce this? I am not using vim in server/client mode, you need to guide me to this problem.

**Comment by AgentCosmic** [comment]
Run `gvim --remote-silent path/to/file`
This will produce first error.
Then run `gvim --remote-silent another/file`
This will produce the second error.

**Comment by weynhamz** [comment]
@AgentCosmic Noop, no error here. 

Could you please test it with just MBE enable? And you use `--remote-silent` without a server instance setup?

**Comment by AgentCosmic** [comment]
I ran it with only pathogen and MBE, still same problem. I'm running on Windows, vim 7.3 patch 1-46.
I'm using `--remote-silent` so I only open files in one instance of gvim.

**Comment by weynhamz** [comment]
You might need to update Vim to a newer version and try again. The ':bd' quiting problem is fixed in a newer Vim version. 

As I can't reproduce your the 'Key not preset' error shown in the screenshots, I can't do anything about, unless you can dig it down a little and provide me with more info.

**Comment by AgentCosmic** [comment]
I've updated to the latest version provided [here](http://tuxproject.de/projects/vim/). The :bd bug is fixed.
However the error message still persist. I have this in my vimrc to wipe any empty buffer. After commenting this out, the error is gone. But I need this code so I don't have an empty buffer in the beggining.

```
autocmd BufAdd * :call <SID>DeleteBufferIfEmpty()
function! s:DeleteBufferIfEmpty()
    " If no name and no content
    if bufname('%') == '' && line('$') == 1 && getline(1) == ''
        bwipe
        " This will trigger filetype detection, mainly to trigger syntax highlighting
        doautocmd BufRead
    endif
endfunction
```

**Comment by weynhamz** [comment]
@AgentCosmic Try the develop branch or my master branch, should be fixed there.

**Comment by weynhamz** [comment]
@AgentCosmic The previous attached commit is buggy, reverted for now, I am working on a fix.

**Comment by weynhamz** [comment]
@AgentCosmic It turns out that not the MBE needs fix, it is your code, just add a 'nested' attribute to your autocmd, which make MBE update its buffer list when you do bwipe in the BufAdd event, then everything works fine.

```
autocmd BufAdd * nested :call <SID>DeleteBufferIfEmpty()
function! s:DeleteBufferIfEmpty()
    " If no name and no content
    if bufname('%') == '' && line('$') == 1 && getline(1) == ''
        bwipe
        " This will trigger filetype detection, mainly to trigger syntax highlighting
        doautocmd BufRead
    endif
endfunction
```
